language: node_js
node_js:
  - "9.7.1"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g typescript@2.7.2
script:
  - tsc
  - mkdir ./public
  - cd ./battleship && npm run buildDeploy
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change